export const PAYMENT_STATUS = {
    PENDING: 'PENDING',
    WAITING_VERIFICATION: 'WAITING_VERIFICATION',
    EXPIRED: 'EXPIRED',
    PAID: 'PAID',
    FAILED: 'FAILED'
}

export const TRIGGER_SOURCE = {
    USER: 'USER',
    SYSTEM: 'SYSTEM',
    BANK: 'BANK'
}

export const STATUS_BANK_PAYMENT = {
    SUCCESSFUL: 'SUCCESSFUL',
    UNSUCCESSFUL: 'UNSUCCESSFUL'
}